name: trivia_mobile
version: 0.1.1+4
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  dio: ^5.4.1
  flutter: 
    sdk: flutter
  flutter_form_builder: ^9.2.1
  get: ^4.6.6
  html_unescape: ^2.0.0
  json_annotation: ^4.8.1
  onboarding: ^4.0.2
  percent_indicator: ^4.2.3

dev_dependencies: 
  build_runner: ^2.4.8
  flutter_test: 
    sdk: flutter
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter: 
  uses-material-design: true

